# Generated by Django 3.1.5 on 2021-03-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=230)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', related_query_name='category_q_name', to='app.category'),
        ),
    ]
