# Generated by Django 3.1.5 on 2021-03-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210304_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('banner_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banner_img', models.ImageField(upload_to='bannerimg')),
                ('active', models.IntegerField()),
            ],
        ),
    ]
