# Generated by Django 3.1.5 on 2021-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bannerslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
