# Generated by Django 3.1.5 on 2021-03-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210304_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cid',
            new_name='cat_id',
        ),
    ]
