# Generated by Django 3.1.5 on 2021-03-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210305_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_stock',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oimg', models.ImageField(upload_to='productimg')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img_name', related_query_name='product_img_q_name', to='app.product')),
            ],
        ),
    ]
