# Generated by Django 3.1.5 on 2021-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210309_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cust_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=70)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=230)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
