# Generated by Django 3.1.5 on 2021-03-20 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOtherDetails',
            fields=[
                ('cust_oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('mobileno', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_r_name', related_query_name='user_rq_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
