# Generated by Django 3.1.5 on 2021-03-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customerotherdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
