# Generated by Django 3.1.5 on 2021-03-23 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_delete_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('custadd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='India', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.BigIntegerField()),
                ('pinocde', models.CharField(max_length=30)),
                ('flat_house_building_company_apartment_no', models.CharField(max_length=200)),
                ('area_colony_street_sector_village', models.CharField(max_length=230)),
                ('landmark', models.CharField(max_length=230)),
                ('town_city', models.CharField(max_length=230)),
                ('state_province_region', models.CharField(max_length=230)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadd_user_r_name', related_query_name='cadd_user_rq_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
