# Generated by Django 3.1.5 on 2021-03-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
