# Generated by Django 3.1.5 on 2021-03-31 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_delete_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('orderid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cart', models.TextField()),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel')], default='Accepted', max_length=200)),
                ('payment_type', models.CharField(max_length=100)),
                ('delivery_date', models.DateTimeField()),
                ('customeraddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerAddress_r_name', related_query_name='CustomerAddress_rq_name', to='app.customeraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_r', related_query_name='order_qr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
