# Generated by Django 3.1.5 on 2021-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orderplaced_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='razorpay_order_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='razorpay_payment_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='razorpay_signature',
            field=models.TextField(null=True),
        ),
    ]
