# Generated by Django 3.1.5 on 2021-04-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210401_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='razorpay_order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='razorpay_payment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='razorpay_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=200),
        ),
    ]
