# Generated by Django 3.1.7 on 2021-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210404_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerachSuggestions',
            fields=[
                ('ss_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ss_name', models.TextField()),
            ],
        ),
    ]
